### ISSUE TITLE
Global variables and functions in javascript are broken in Release Candidate

### ISSUE THREAD

**Issue by rhisling** [one-dark/jetbrains-one-dark-theme#106]
The global variables and global functions are in weird color.
![image](https://user-images.githubusercontent.com/35667987/69370256-794a8580-0c52-11ea-9d1b-54d0d319bf61.png)

**Comment by mskelton** [comment]
Thanks for the report.  I'll look into this tonight.

**Comment by mskelton** [comment]
I just released 3.3.1 which may fix it.  I've been noticing some really odd behavior lately with the syntax highlighting so that's why I'm saying that it "may" fix it 😄

**Comment by rhisling** [comment]
Thanks but unfortunately it didn't fix it. I found that they don't inherit from 'Language defaults' anymore.
![image](https://user-images.githubusercontent.com/35667987/69399763-387b5c80-0ca4-11ea-8853-98ee86eb7f33.png)
On a side note, thanks for this theme. I use your VSCode theme as well :)

**Comment by mskelton** [comment]
Well that's unfortunate.  It seems to be the same as the bug reported in #104 which is being tracked by JetBrains in this issue: https://youtrack.jetbrains.com/issue/GO-8117.

I wish I could do more but at this point I think it is a waiting game until JetBrains fixes the bug.

**Comment by rhisling** [comment]
Thanks a lot. I think python is also broken and it looks like they won't be fixing it in 2019.3.

**Comment by mskelton** [comment]
Yeah, I think it's pretty unfortunate that they are letting a bug like this get into their next release version.  Seems like a lot of people will be complaining when the actual version comes out.  As a note, you'll probably be able to change the colors manually until the JetBrains fix comes out.

**Comment by mskelton** [comment]
I'm going to close this since it will probably be fixed without any change to the plugin in the next version.
